# Generated by Django 3.1.7 on 2021-03-03 23:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('desktop_laptop_nas', models.CharField(choices=[('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop'), ('NAS', 'Nas')], default='DESKTOP', max_length=15, verbose_name='Desktop/Laptop/NAS')),
                ('os', models.CharField(max_length=100)),
                ('physical_virtual', models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual')], default='PHYSICAL', max_length=15, verbose_name='Physical/Virtual')),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('administrator', models.CharField(blank=True, max_length=100)),
                ('uofa_tag_number', models.CharField(blank=True, max_length=15)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=15)),
                ('storage', models.CharField(blank=True, max_length=15)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OFF', 'Off'), ('TEMP', 'Temp'), ('SURPLUS', 'Surplus'), ('STALLED', 'Stalled'), ('SPARE', 'Spare'), ('RETIRED', 'Retired'), ('MISSING', 'Missing'), ('IPALIAS', 'Ipalias'), ('FLOATER', 'Floater')], default='ACTIVE', max_length=15, verbose_name='Status')),
                ('rack', models.CharField(max_length=15)),
                ('scitech_access', models.BooleanField(null=True)),
                ('power_up_priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('U', 'Unknown')], default='U', max_length=1)),
                ('support_team', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('latest_information_update_date', models.DateTimeField(auto_now=True)),
                ('date_added_to_database', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'WebCMDBapi_computer',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servername', models.CharField(max_length=100)),
                ('fqdn', models.CharField(blank=True, max_length=100)),
                ('used_for', models.CharField(blank=True, max_length=100)),
                ('application', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(choices=[('TEACHING/LEARNING', 'Teaching/Learning'), ('RESEARCH', 'Research'), ('ADMINISTRATION', 'Administration'), ('MULTIPLE', 'Multiple'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20, verbose_name='Services support by the server')),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('os', models.CharField(choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='OS')),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('cpu_counts', models.CharField(blank=True, max_length=10)),
                ('ram', models.CharField(blank=True, max_length=10)),
                ('storage_installed', models.CharField(blank=True, max_length=10)),
                ('storage_used', models.CharField(blank=True, max_length=10)),
                ('part_of_ActiveDirectoryDomain', models.BooleanField(default=False)),
                ('domain_name', models.CharField(blank=True, max_length=100)),
                ('server_type', models.CharField(blank=True, choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual'), ('CLOUD', 'Cloud')], max_length=20, null=True, verbose_name='Server Type')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('location_access', models.CharField(blank=True, max_length=100)),
                ('virtual_environment', models.CharField(blank=True, choices=[('VMWARE', 'Vmware'), ('HYPERV', 'Hyperv'), ('OPENSTACK', 'Openstack'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Virtual Environment')),
                ('cloud_provider', models.CharField(blank=True, choices=[('AZURE', 'Azure'), ('AWS', 'Aws'), ('GCP', 'Gcp'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Cloud Provider')),
                ('firewall', models.BooleanField(null=True)),
                ('firewall_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('backup', models.BooleanField(null=True)),
                ('backup_type', models.CharField(blank=True, max_length=20)),
                ('backup_system', models.CharField(blank=True, max_length=20)),
                ('retention_period', models.CharField(blank=True, max_length=20)),
                ('monitor', models.BooleanField(null=True)),
                ('monitor_server', models.CharField(blank=True, max_length=20)),
                ('maintenance_windows', models.BooleanField(null=True)),
                ('patching_schedule', models.CharField(blank=True, max_length=100)),
                ('legal_requirements', models.BooleanField(null=True)),
                ('support_hours', models.CharField(blank=True, max_length=50)),
                ('contact_technical', models.TextField(blank=True)),
                ('contact_business', models.TextField(blank=True)),
                ('device_owner', models.CharField(blank=True, max_length=50)),
                ('licensing', models.CharField(blank=True, max_length=50)),
                ('comment_service_application', models.TextField(blank=True)),
                ('comment_server', models.TextField(blank=True)),
                ('comment_issues', models.TextField(blank=True)),
                ('latest_information_update_date', models.DateTimeField(auto_now=True)),
                ('date_added_to_database', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'WebCMDBapi_server',
            },
        ),
    ]
