# Generated by Django 3.1.7 on 2021-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCMDBapi', '0002_auto_20210304_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
