# Generated by Django 3.1.7 on 2021-03-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCMDBapi', '0003_auto_20210304_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='computer',
            name='physical_virtual',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
