# Generated by Django 3.1.7 on 2021-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCMDBapi', '0004_auto_20210311_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='desktop_laptop_nas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
