# Generated by Django 3.1.7 on 2021-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCMDBapi', '0005_auto_20210316_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='firewall',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='host_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='host_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='trustlevel',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
