# Generated by Django 3.1.7 on 2021-04-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCMDBapi', '0006_auto_20210419_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
