# Generated by Django 3.1.7 on 2021-04-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCMDBapi', '0007_auto_20210419_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='os_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
